### ISSUE TITLE
Support API Authentication

### ISSUE THREAD

**Issue by ledongthuc** [ledongthuc/awssecretsmanagerui#5]
# 1. Summary

 - We need to support a better authentication method that users will enter username and password on the login page.
 - In the scope of this issue, we focus on Backend tasks that including implementing an API to authenticate username, password and update the authentication middleware to handle JWT token.

# 2. Current Status

 - Currently, AWS Secrets Manager UI only support Auth Basic for authentication: https://github.com/ledongthuc/awssecretsmanagerui/blob/main/server/main.go#L31
 - We load user credentials from variable environments to validate https://github.com/ledongthuc/awssecretsmanagerui/blob/58a5f6f5df7823d968ccc2b4fbfb6c5637a35217/server/actions/auth.go#L24
 - Password is based on SHA-256.

| Variable environment | Note |
| ------- | ------- |
| AUTH_ACCOUNTS | account credentials, e.g. "{\"user1\":\"5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5\", \"user1\":\"5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5\"}" |
| AUTH_ENABLED | true/false to enable/disable authentication feature. Default: false |

# 3. Todo

**3.1. Support multiple authentication types**

 - Add a new variable type to control authentication type.

| Variable environment | Note |
| ------- | ------- |
| AUTH_TYPE | Support 2 types: `auth_basic` and `login_form`. Default: `login_form` |

![AWSSecretManagerUI-AuthFlow](https://user-images.githubusercontent.com/1828895/124166728-81f87400-daa3-11eb-92da-aa7e309ac90f.png)

**3.2. Implement new API to login**

 - Implement an API that has input is username/password and output is an access token.
 - API handle will validate username/password same with auth basic flow, if it's successfully, generate the access token.
 - The access token is the JWT token that is generated by JWT_SIGNATURE_KEY (is defined in next section)
 - JWT example: https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsInVzZXJuYW1lIjoidXNlcjEiLCJpYXQiOjE1MTYyMzkwMjJ9.GelYwSAebg7bKmZlVjmXByRKW7GV4oQASSLqGoMj1FY

**3.3. JWT Token**

 - Add a new variable to store the JWT sign key.

| Variable environment | Note |
| ------- | ------- |
| JWT_SIGNATURE_KEY | e.g. "WaLTyStaGNeWMEDE" |

 - JWT use algo: HS256.
 -JWT example: https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsInVzZXJuYW1lIjoidXNlcjEiLCJpYXQiOjE1MTYyMzkwMjJ9.GelYwSAebg7bKmZlVjmXByRKW7GV4oQASSLqGoMj1FY

**3.3. Update middleware to validate token from API login**

 - Add new middleware that is added into system if AUTH_ENABLED = true and AUTH_TYPE = "login_form"
 - Logic of middleware will get the request's header, parse header name "Authorization" and value will in the form "Bearer <token>
 - Middleware get token and verify it by JWT token, if it's valid, it means the request passes the authentication

**Comment by duysmile** [comment]
Response example
```
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjUyNTAwOTEsImlhdCI6MTYyNTI1MDA4MSwic3ViIjoidXNlcjEifQ.2PhlP-53K8ltR6QzngOXJqhW0APUeYUBk6wPKciPIpI",
    "expiry": 10,
    "created": "2021-07-03T01:21:21.046331+07:00"
}
```

**Comment by duysmile** [comment]
Add variable environment to set expiring time for JWT

Variable environment | Note
-- | --
JWT_EXPIRY_TIME | expiring time in second(s) e.g: 10

**Comment by ledongthuc** [comment]
Implemented.
